### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by LeonidKokhnovich** [alexejn/LogView#1]
Hi!

Thanks for your effort to create such a functional component for viewing logs on mobile devices.

I see currently it can be added as SPM dependency. It would be really great to add Cocoapods support too so the teams with existing Cocoapods infrastructure could pull it too without adding SPM (that's larger initiative for many teams out there).

This will hopefully also increase project reach throughout many dev teams.

Thank you!

**Comment by alexejn** [comment]
I'm sorry, but there are no plans to support cocoapods.
